---
abstract: 'Basic cross-platform tests for scripts'
author:
  - 'Graham Ollis <plicease@cpan.org>'
  - 'Adam Kennedy'
build_requires:
  Test2::V0: '0.000060'
  perl: '5.008001'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008001'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Script
provides:
  Test::Script:
    file: lib/Test/Script.pm
    version: '1.29'
requires:
  Capture::Tiny: '0'
  File::Spec: '0.80'
  IO::Handle: '0'
  Probe::Perl: '0.01'
  Test2::API: '1.302015'
  Text::ParseWords: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/uperl/Test-Script/issues
  homepage: https://metacpan.org/pod/Test::Script
  repository: git://github.com/uperl/Test-Script.git
version: '1.29'
x_contributors:
  - 'Adam Kennedy'
  - 'Graham Ollis <plicease@cpan.org>'
  - 'Brendan Byrd'
  - 'Chris White <cxw@cpan.org>'
  - 'John Karr (BRAINBUZ)'
x_generated_by_perl: v5.33.9
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
x_use_unsafe_inc: 0
